# Generated by Django 4.2.5 on 2023-10-31 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='image',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='desc',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='switch',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='switch',
            name='product_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
